# Generated by Django 6.0.2 on 2026-03-10 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_name", models.CharField(max_length=255, unique=True)),
                ("pdf_text", models.TextField()),
                ("pdf_text_raw", models.TextField()),
                ("contexts", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField(blank=True)),
                ("prediction_time", models.FloatField(blank=True, null=True)),
                ("original_predictions", models.JSONField(default=dict)),
                ("is_validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(null=True)),
                ("validated_predictions", models.JSONField(blank=True, default=dict)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
