# Generated by Django 6.0.2 on 2026-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="pdf_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="validated_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
