# Generated by Django 6.0.2 on 2026-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_document_pdf_name_alter_document_validated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="validated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
