# Generated by Django 6.0.2 on 2026-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_document_validated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_text_raw",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
