MRAE_URLS = {
    "Auvergne-Rhône-Alpes": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r304.html",
    "Bourgogne Franche-Comté": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r305.html",
    "Bretagne": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r306.html",
    "Centre-Val de Loire": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r307.html",
    "Corse": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r308.html",
    "Grand Est": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r302.html",
    "Guadeloupe": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r315.html",
    "Guyane": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r316.html",
    "Hauts-de-France": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r311.html",
    "Île-de-France": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r309.html",
    "La Réunion": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r319.html",
    "Martinique": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r317.html",
    "Mayotte": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r318.html",
    "Nouvelle-Aquitaine": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r303.html",
    "Normandie": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r312.html",
    "Occitanie": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r310.html",
    "Pays de la Loire": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r313.html",
    "Provence-Alpes-Côte d'Azur": "https://www.mrae.developpement-durable.gouv.fr/avis-rendus-sur-projets-r314.html",
}
